sudo: required
language: c++
services:
- docker

script:
- docker build -t intel1.2:$COMMIT -f  Dockerfile.intel_ocl1.2_cpu .
- docker build -t intel2.0:$COMMIT -f  Dockerfile.intel_ocl2.0_cpu .
- docker build -t intel2.0:$COMMIT -f  Dockerfile.nvidia .

env:
  - COMMIT=${TRAVIS_COMMIT::8}
