sudo: required
language: c
services:
- docker
before_install:
- echo $DOCKER_EMAIL
- docker build -t cwpearson/chai-intel-opencl1.2-cpu -f  Dockerfile.intel_ocl1.2_cpu
  .
script:
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/BFS  &&
  ./bfs"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/BS   &&
  ./bs"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/CEDD
  && ./cedd"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/CEDT
  && ./cedt"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/HSTI
  && ./hsti"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/HSTO
  && ./hsto"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/PAD  &&
  ./pad"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/RSCD
  && ./rscd"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/RSCT
  && ./rsct"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/SC   &&
  ./sc"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/SSSP
  && ./sssp"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/TQ   &&
  ./tq"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/TQH  &&
  ./tqh"
- docker run -it cwpearson/chai-intel-opencl1.2-cpu bash -c "cd chai/OpenCL1.2/TRNS
  && ./trns"

env:
  global:
    secure: WyFJbUSBamKMsNSgSp/Dp0LRynTku7alqJeZaKSWSjc8sNEbqbiDyyo4RVXkXSZTx+LN/IDihzRTQmhIvq2E4sKUpcSpWu/OWVUG6OmI2KJuiiJSjVrwfbOndlgNytjApzzPtLRzhgpWK207jtdgN2coRsZVgQF0OTRthITiSF4xzCzp5QXt758+wL3YUyKK6fXM9Jp6kKHd8LRf1gai7nl5AeX5VdAmPU18mrwc1LHdT0TWR7pDgHpqWacxVCdykqedxLgvJVU0CXXyHkaoKj61cNGydNQmzq2IjeYeNYrgvQ/ZzsJsVvSyB8g7rkRR0YnkiAHrYD29B/ZxUeTtimCUB488hN7HeyG58EjETUpjUqwxshPRnSc1q+pn3O487HcNkD/khiUKPM5RqBsX8PYrqfAStQJWa/R0PRY5zg1JofaWq4OvhK/2OB07A5VkYvm2E9I9CsXG+vuPGWoKiFoSz9ZihNVCbbxI2Dp8ivEl519N90uuoxbTIIUff4p9+6aFZj4kMTqyobYng36DM1dclRZFkCwF+VIEc05HGKffDM4W+tT4xTG/JelVqJpw/WysmzJAVgeCsLUzmEo/nCs9XQEXubnMhgpIvjzHq9Dwkh1mn+8D3pcjsaaBcpIQuCYguuUPFEWjPCxEJ9iJ6d3o+/Yqpbr1UWX9ZZZrmJQ=
